lst = ['+3', '+4', '+5', '+6']
a = dict.fromkeys(lst)
print(a)
a = dict.fromkeys(lst, 'kod strani')
print(a)
a.clear()
print(a)
a = {True: 1, False: 'loch', 'list': [1, 2, 3], 5: 5}
b = a.copy()
c = dict(a)
print(b, c)
print(a.get('a', False))
print(b.setdefault('list'), b)
b.setdefault(888)
b.setdefault(3, 'vasya')
print(b)
bb = b.pop(True)
print(b, bb)
print(b.pop(777, 2222))
print(b)
bbb = b.popitem()
print(b, bbb)
cc = c.keys()
ccc = c.values()
cccc = c.items()
print(cc, ccc, cccc)
